# Generated by Django 5.2.1 on 2025-05-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contactoPrincipal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intercambios.tipocontacto'),
        ),
    ]
