# Generated by Django 5.2.1 on 2025-05-16 20:44

import intercambios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=intercambios.models.ruta_portadas),
        ),
    ]
