# Generated by Django 5.2.1 on 2025-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0004_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
