# Generated by Django 4.1 on 2025-05-13 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libros/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTrueque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('libro_deseado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_deseados', to='trueque_libros.libro')),
                ('libro_ofrecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_ofrecidos', to='trueque_libros.libro')),
                ('usuario_deseado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_deseados', to=settings.AUTH_USER_MODEL)),
                ('usuario_ofrecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_ofrecidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
